#
#
#
INT_ZIP = './Phuket_INSAR_ISCE_BURST'
RESULT = './PK_SOUTH_ASC'
#
NEW_PAIRS = [ ['001','003'], ['005','008'], ['013','015'] , ['014','016'] ]
FONT = 12
VLINE_DT = [ "2024-08-17 23:11:10", 
          "2024-08-29 23:11:10" ]
